---
- name: run pgsql backup
  hosts: pgsql
  remote_user: nurlan
  gather_facts: no
  become: yes

  tasks:
  - name: backup PostgreSQL databases on server 10.204.11.47
    shell: bash /home/nurlan/backup.sh
    register: backup

  - debug:
      var: backup.stdout

  - name: find all files that are older than 10 days
    find:
      paths: /home/nurlan/dumps
      age: 10d
      recurse: yes
    register: filesOlderThan10
  - name: remove older than 10
    file:
       path: "{{ item.path }}" 
       state: absent
    with_items: "{{ filesOlderThan10.files }}"